### PR TITLE
Tk less verbose

### PR DESCRIPTION
**Pull request by takabayashi**
To test:

Just build hadoop and dev in order:

`REBUILD_HADOOP=true vagrant up hadoop`
`REBUILD_DEV=true vagrant up dev`

Build marvin toolbox:
`workon python-toolbox-env`
`make marvin`

Than build iris engine to test all the pipeline workflow:
`marvin engine-generateenv /vagrant/projects/public-engines/iris-species-engine/`
`workon workon iris-species-engine-env`
`make marvin`

Download engine executor:
`wget https://s3.amazonaws.com/marvin-engine-executor/marvin-engine-executor-assembly-0.0.1.jar -O marvin-engine-executor.jar`

Start engine executor http server:
`marvin engine-httpserver`

Send a http post to http://localhost:8000/pipeline endpoint:
`curl -H "Content-Type: application/json" -X POST http://localhost:8000/pipeline -d {}`

Check (using a web browser) if artifacts are successfully saved in there path:
http://localhost:50070/explorer.html#/tmp/marvin/iris_species/v0.0.1

### CODE REVIEW

**Comment by lucasbm88** [comment]
Improvements look great, although I had an issue when trying to test the procedure described above: 
 - After bringing the dev VM up, it was not possible to run the command "workon python-toolbox-env, the error was 
```
vagrant@marvin-dev:~$ workon python-toolbox-env
ERROR: Environment 'python-toolbox-env' does not exist. Create it with 'mkvirtualenv python-toolbox-env'.
```
 - I tryed running mkvirtualenv to create the toolbox env, but it failed with:
```
OSError: [Errno 13] Permission denied: '/home/vagrant/.virtualenvs/python-toolbox-env'
```

**Comment by takabayashi** [comment]
Please try again... save the log and attach here.

first of all destroy your box:
`vagrant destroy dev`

remove your core cached box:
`vagrant box remove marvin-ai/marvin-platform-core 0.0.2`

than rebuild again redirecting the log:
`REBUILD_DEV=true vagrant up dev >> rebuild_dev.log`

and attach the log file here...let's see what is going on...

**Comment by lucasbm88** [comment]
Check the log attached 
[log-shell.txt](https://github.com/marvin-ai/marvin-vagrant-dev/files/1436081/log-shell.txt)

**Comment by takabayashi** [comment]
Ok...I got a little bug!
Please pull last branch code version and try again...

**Comment by lucasbm88** [comment]
The command line to create virtualenv was just being printed, I added a system call to execute it. Also moved the chown fix to the projects.rb, for some reason permissions were being modified after the python.sh provision file run. I commited those minor fixes, tested and will merge.

**Review by lucasbm88 — APPROVED** [review]
After some minor fixes the test was successful

**Pull request merged**
